### ISSUE TITLE
Velocity Version

### ISSUE THREAD

**Issue by nothub** [zeroBzeroT/AnarchyQueue#76]
Reproducible by running `runServer` and then `runVelocity` gradle tasks,
on [`velocity`](https://github.com/zeroBzeroT/AnarchyQueue/tree/velocity) branch:

```
[16:44:02 INFO]: Booting up Velocity 3.3.0-SNAPSHOT (git-5154f029-b404)...
[16:44:02 INFO]: Loading localizations...
[16:44:02 INFO]: Connections will use epoll channels, libdeflate (Linux x86_64) compression, OpenSSL 3.0.x (Linux x86_64) ciphers
[16:44:02 INFO]: Loading plugins...
[16:44:02 INFO]: Loaded plugin anarchyqueue 2.0.2-SNAPSHOT by bierdosenhalter, nothub
[16:44:02 INFO]: Loaded 1 plugins
[16:44:02 INFO]: Listening on /[0:0:0:0:0:0:0:0%0]:25565
[16:44:02 INFO]: Done (0.47s)!
[16:44:10 INFO]: [connected player] CPacketAnimation (/127.0.0.1:48118) has connected
[16:44:10 ERROR]: [connected player] CPacketAnimation (/127.0.0.1:48118): unable to connect to server main
io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /127.0.0.1:25567
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
	at io.netty.channel.unix.Errors.newConnectException0(Errors.java:166) ~[404.jar:3.3.0-SNAPSHOT (git-5154f029-b404)]
	at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:131) ~[404.jar:3.3.0-SNAPSHOT (git-5154f029-b404)]
	at io.netty.channel.unix.Socket.finishConnect(Socket.java:359) ~[404.jar:3.3.0-SNAPSHOT (git-5154f029-b404)]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:711) ~[404.jar:3.3.0-SNAPSHOT (git-5154f029-b404)]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:688) ~[404.jar:3.3.0-SNAPSHOT (git-5154f029-b404)]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567) ~[404.jar:3.3.0-SNAPSHOT (git-5154f029-b404)]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[404.jar:3.3.0-SNAPSHOT (git-5154f029-b404)]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[404.jar:3.3.0-SNAPSHOT (git-5154f029-b404)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[404.jar:3.3.0-SNAPSHOT (git-5154f029-b404)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[404.jar:3.3.0-SNAPSHOT (git-5154f029-b404)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[404.jar:3.3.0-SNAPSHOT (git-5154f029-b404)]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[16:44:10 INFO]: [connected player] CPacketAnimation (/127.0.0.1:48118) has disconnected: Unable to connect you to main. Please try again later.

```

**Comment by nothub** [comment]
fixed
